#!/usr/bin/env bash
# This script is designed to back up and compress databases.

# Declare variables for the current day, month, and year.
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
