#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Stop Nginx if it's running
service nginx stop

# Replace 'user' directive in nginx.conf to run Nginx as nginx user
sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf

# Restart Nginx
service nginx start

# Check if Nginx is running as nginx user
ps aux | grep nginx

# Check if Nginx is listening on port 8080
nc -z 0 8080
